version: '3'
services:
  migrate:
    image: migrate/migrate
    restart: on-failure:5
    volumes:
        - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:${PGPORT}/${PGDBNAME}?user=${PGUSER}&password=${PGPASSWORD}&sslmode=disable", "up"]
    depends_on: 
      - postgres
  imager:
    build: ../.
    environment: 
        - AWS_SDK_LOAD_CONFIG=true
        - BUCKETNAME=${BUCKETNAME}
        - PGDBNAME=${PGDBNAME}
        - PGUSER=${PGUSER}
        - PGPASSWORD=${PGPASSWORD}
        - PGHOST=postgres
        - PGPORT=${PGPORT}
    volumes: 
      - ~/.aws:/root/.aws
    ports:
      - "8080:8080"
    depends_on: 
      - postgres
  postgres:
    image: "postgres"
    restart: always
    environment: 
        - POSTGRES_DB=${PGDBNAME}
        - POSTGRES_USER=${PGUSER}
        - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
        - pgdbdata:/var/lib/postgresql/data
volumes:
    pgdbdata:
